 <?php
include_once("./includes/__header__.php");
include_once("./includes/__navbar__.php");
include_once("./includes/components/__hero__section__.php");
include_once("./includes/components/__features__.php");
include_once("./includes/components/__testimoni__.php");
include_once("./includes/components/__cta__.php");
include_once("./includes/__footer__.php");
 ?>